# Generated by Django 3.2.12 on 2022-03-16 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtmosCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acname', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PondCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcname', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProminentParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppname', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Combinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition', models.CharField(max_length=500)),
                ('acname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.atmoscondition')),
                ('pcname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.pondcondition')),
                ('ppname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.prominentparameter')),
            ],
            options={
                'unique_together': {('ppname', 'acname', 'pcname')},
            },
        ),
    ]
