# Generated by Django 3.2.12 on 2022-03-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_prominentparameter_optimalrange'),
    ]

    operations = [
        migrations.AddField(
            model_name='prominentparameter',
            name='units',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
