# Generated by Django 3.2.12 on 2022-03-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_prominentparameter_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='prominentparameter',
            name='lower_boundary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prominentparameter',
            name='upper_boundary',
            field=models.IntegerField(default=1),
        ),
    ]
