# Generated by Django 3.2.12 on 2022-03-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_prominentparameter_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prominentparameter',
            name='lower_boundary',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='prominentparameter',
            name='upper_boundary',
            field=models.FloatField(),
        ),
    ]
